apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multicluster-engine

resources:
- deployment.yaml
- rbac.yaml
- service.yaml

images:
- name: vmware-hcp-agent-companion
  newName: quay.io/jpacker/vmware-hcp-agent-companion
  newTag: "0.5.3"
